# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba992d463c52ddab890807c871e93c0fbb09a1adcd398ae155bbe976c22dfcb6f670fdf12d1557296d56eb67401bdcacd5584a6a708ac612a351729433406e2

test:
  secret_key_base: 126a62bbdaf3113b61c443ef5c68ed0e2a41947b7cff2d959659a3690d809f62684e08fc6b804ece09d6d2dbdb5a4647b987331b9c214d4f53c935eff541133e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
